project:
  type: website
  output-dir: docs
  resources:
    - img/**

website:
  search: 
    location: navbar
    type: overlay
  navbar:
    logo: img/power-rangers/purple.png
    logo-href: "#"
    logo-alt: "Power Rangers Team"
    left:
      - text: "home"
        href: index.qmd
      - text: "cv"
        href: cv.qmd
      - text: "materials"
        href: open-materials.qmd
      - text: "contact"
        href: contact.qmd
format:
  html: 
    theme:
      light: yeti
    fontsize: 1.2em
    linestretch: 1.7
    css: styles.css
    toc: true
    smooth-scroll: true

